# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: e2e tests cypress app

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: './app'
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Prepare api to tests
      run: npm --prefix ../api ci
    - run: npm run api &
    - run: npm ci
    - run: npm run web:test:env &
    - name: Running e2e cypress   
      run: npx cross-env WEB_SERVER_URL=http://localhost:3300 npm run cy:headless